### ISSUE TITLE
SetMarginModeAsync for PerpetualFuturesApi

### ISSUE THREAD

**Issue by Akunin88** [JKorf/BingX.Net#13]
Method PerpetualFuturesApi.Account.SetMarginModeAsync() does not change margin type.

I have **Cross** margin for the contract **MANA-USDT** and try to change it by using method SetMarginModeAsync("MANA-USDT", MarginMode.Isolated).

Then I use method PerpetualFuturesApi.Account.GetMarginModeAsync("MANA-USDT") and I see that margin still have value  **Cross**.

**Comment by JKorf** [comment]
Had to do some research but should be fixed in the latest version

**Comment by Akunin88** [comment]
It works good for changing Isolated margin mode to Cross margin mode.
But it does not change Cross margin mode to Isolated margin mode
