### ISSUE TITLE
Nuget not updating

### ISSUE THREAD

**Issue by akaitrade** [JKorf/BingX.Net#14]
Nuget is stuck on version 1.5.0

: https://www.nuget.org/packages/JK.BingX.Net

**Comment by JKorf** [comment]
Yes, there has been an issue with my NuGet account, I'm in contact with support for getting it fixed. But until then the latest versions are not available from NuGet. Easiest way to get the latest version is to add GitHub packages as source to the NuGet package manager. 

Once my account is functional again I'll update the package on NuGet as well.

**Comment by JKorf** [comment]
Latest version is available again
