### ISSUE TITLE
FeeAsset is Empty

### ISSUE THREAD

**Issue by Dosihris** [JKorf/BingX.Net#16]
Hey Jan, 

I used the bingx restclient to load order infos, everything is filled, but not the FeeAsset

**To Reproduce**
Endpoint: restClient.SpotApi.Trading.GetOrdersAsync(tradeSymbol)

**Expected behavior**
All properties filled, but FeeAsset is not.

![image](https://github.com/user-attachments/assets/20df1717-4d94-4ed2-a8a1-c98f3d7445ba)

**Comment by JKorf** [comment]
Hi, based on the documentation the FeeAsset is only returned when requesting order details for one specific order (SpotApi.Trading.GetOrderAsync), it's not returned when requesting multiple orders.

**Comment by Dosihris** [comment]
Ok, i see, thank you for checking...
