### ISSUE TITLE
Open Price in Future Position not set

### ISSUE THREAD

**Issue by Dosihris** [JKorf/BingX.Net#17]
Hey Jan, 
i am reading the done future positions from BingX.

**To Reproduce**
 var historicPositions = await _restClient.PerpetualFuturesApi.Trading.GetClosedOrdersAsync();

**Expected behavior**
Here is a screenshot from a position i read in Visual Studio. You can see that AveragePrice/Price is near the close price, but i dont see the open price anywhere (must be around 5.79993)
![image](https://github.com/user-attachments/assets/e5208fd6-465b-451e-93ed-83c87803b16f)

Thats a screenshot from BingX with the real position. 
![image](https://github.com/user-attachments/assets/1a1aa68b-f1e5-42f8-94b3-5a32f6a786fa)

**Comment by JKorf** [comment]
Hi, the endpoint you're referring to is only returning closed orders, not closed positions. Another endpoint for getting the position history has been added though, I'll implement that one. Probably will be available tomorrow.

**Comment by JKorf** [comment]
It's available in the latest version
