### ISSUE TITLE
Issue with TimeInForce field type of the BingXFuturesPlaceOrderRequest class

### ISSUE THREAD

**Issue by QuickLeopard** [JKorf/BingX.Net#21]
**Describe the bug**

There is a mistake in the TimeInForce field type of the BingXFuturesPlaceOrderRequest class. It has TriggerType type in your code.

```
public record BingXFuturesPlaceOrderRequest
{
   [JsonPropertyName("timeInForce")]
   [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
   public TriggerType? TimeInForce { get; set; }
}
```

**To Reproduce**
Call BingXFuturesPlaceOrderRequest class constructor, like this:
```
new BingXFuturesPlaceOrderRequest() 
{ 
    Symbol = "BTCUSD",
    Price = 100000,
    Quantity = 0.1,
    Side =  OrderSide.Buy,
    OrderType = FuturesOrderType.Limit,
    TimeInForce = ?
};
```

**Expected behavior**
Expecting to change TimeInForce field to correct type.

**Debug logging**
Add debug logging related to the issue. Enable Debug logging in the client options by settings LogLevel to Debug.

**Comment by JKorf** [comment]
Hi, should be fixed in the latest version
