### ISSUE TITLE
Placing market order for PerpetualFuturesApi

### ISSUE THREAD

**Issue by Akunin88** [JKorf/BingX.Net#6]
When I use method restClient.PerpetualFuturesApi.Trading.PlaceOrderAsync and place **market** order with params (see picture)
**quantity = 5**, I want to place order with 5 USDT but api try to place order with quantity in 5 BTC.
Probably it is bingX api problem.
![11](https://github.com/JKorf/BingX.Net/assets/40500500/0ae60f73-d0ad-4371-b34a-cc0806387f66)
![22](https://github.com/JKorf/BingX.Net/assets/40500500/9df0109d-3fa3-4771-abd4-2015a019b075)

**Comment by JKorf** [comment]
Hi, it seems the API does not currently support placing orders by specifying value as quantity:

![image](https://github.com/JKorf/BingX.Net/assets/8448172/991bdca1-86fe-40b5-a18b-33930190e41e)

**Comment by Akunin88** [comment]
Thank you. It's look strange
