### ISSUE TITLE
Can't convert bool value in PerpetualFuturesApi -> GetContractsAsync method

### ISSUE THREAD

**Issue by 30yavash** [JKorf/BingX.Net#7]
**Describe the bug**
sometime boolean value response from api as json string, isn't true or false ! BingX return just empty string "" so the following code doesn't convert from json string to Object related Model

**To Reproduce**
var contracts = await _bingXClient.PerpetualFuturesApi.ExchangeData.GetContractsAsync();

**Debug logging**
{[DeserializeError] Unknown exception: Can't convert bool value 25 {"code":0,"msg":"","data":[{"contractId":"100","symbol":"BTC-USDT","size":"0.0001","quantityPrecision":4,"pricePrecision":1,"feeRate":0.0005,"makerFeeRate":0.0002,"takerFeeRate":0.0005,"tradeMinLimit":0,"tradeMinQuantity":0.0001,"tradeMinUSDT":2,"maxLongLeverage":125,"maxShortLeverage":125,"currency":"USDT","asset":"BTC","status":1,"apiStateOpen":"true","apiStateClose":"true","ensureTrigger":true,"triggerFeeRate":"0.00020000"},{"contractId":"101","symbol":"ETH-USDT","size":"0.01","quantityPrecision":2,"pricePrecision":2,"feeRate":0.0005,"makerFeeRate":0.0002,"takerFeeRate":0.0005,"tradeMinLimit":0,"tradeMinQuantity":0.01,"tradeMinUSDT":2,"maxLongLeverage":125,"maxShortLeverage":125,"currency":"USDT","asset":"ETH","status":1,"apiStateOpen":"true","apiStateClose":"true","ensureTrigger":true,"triggerFeeRate":"0.00010000"},{"contractId":"103","symbol":"LINK-USDT","size":"0.1","quantityPrecision":1,"pricePrecision":3,"feeRate":0.0005,"makerFeeRate":0.0002,"takerFeeRate":0.0005,"tradeMinLimit":0,"tradeMinQuantity":0.1,"tradeMinUSDT":2,"maxLongLeverage":5,"maxShortLeverage":5,"currency":"USDT","asset":"LINK","status":1,"apiStateOpen":"true","apiStateClose":"true","ensureTrigger":true,"triggerFeeRate":"0.00025000"},{"contractId":"100002","symbol":"BCH-USDT","size":"0.01","quantityPrecision":2,"pricePrecision":2,"feeRate":0.0005,"makerFeeRate":0.0002,"takerFeeRate":0.0005,"tradeMinLimit":0,"tradeMinQuantity":0.01,"tradeMinUSDT":2,"maxLongLeverage":5,"maxShortLeverage":5,"currency":"USDT","asset":"BCH","status":1,"apiStateOpen":"true","apiStateClose":"true","ensureTrigger":true,"triggerFeeRate":"0.00075000"},

**Comment by 30yavash** [comment]
in this case
BingXContract.Online in responsible for this Error:
namespace BingX.Net.Objects.Models
{
    public record BingXContract
    {
        [JsonPropertyName("status")]
        public bool Online { get; set; }
    }
}

look at this real example, STARL-USDT symbol cant handle with api because of apiState flag and its status is 25, its mean status isnt boolean:

{"contractId":"100279","symbol":"STARL-USDT","size":"1","quantityPrecision":0,"pricePrecision":9,"feeRate":0.0005,"makerFeeRate":0.0002,"takerFeeRate":0.0005,"tradeMinLimit":0,"tradeMinQuantity":422288,"tradeMinUSDT":2,"maxLongLeverage":5,"maxShortLeverage":5,"currency":"USDT","asset":"STARL","status":25,"apiStateOpen":"false","apiStateClose":"false","ensureTrigger":true,"triggerFeeRate":"0.00160000"}

**Comment by JKorf** [comment]
Hm yes I see. The documentation only mentions status values 0 or 1 which maps to a boolean just fine. However when trying to parse 25 as a boolean it fails. I'll update the property to an int as there are appearantly more than 2 values it can be

**Comment by JKorf** [comment]
Fixed it in 1.3.1
