### ISSUE TITLE
Error gettings exchange contracts

### ISSUE THREAD

**Issue by slavslavin** [JKorf/BingX.Net#8]
Hi,
I use JK.BingX.Net:
` <PackageReference Include="JK.BingX.Net" Version="1.3.0" />`

I try to get BingX futures available contracts, but get an error:
![изображение](https://github.com/JKorf/BingX.Net/assets/116277940/575be56b-49aa-4943-be69-b5ee747d0e20)
In previous versions of library it worked. Any ideas?

Thanks, Tim

**Comment by JKorf** [comment]
Hi, this is because of the API returning an undocumented value. It has already been fixed in version 1.3.1
