### ISSUE TITLE
No data updates in user order updates stream

### ISSUE THREAD

**Issue by Akunin88** [JKorf/BingX.Net#9]
When I place orders via API there are no any updates in the user's stream. I use **jk.bingx.net 1.3.1**.
For subscription (**onOrderUpdate**) I use method **socketClient.PerpetualFuturesApi.SubscribeToUserDataUpdatesAsync**
I place orders (market or limit) by using method **restClient.PerpetualFuturesApi.Trading.PlaceOrderAsync**

In the same time when I place/cancel limit/market orders using web-browser then I receive updates in the user's stream.

Probably there are some errors with data parsing (see picture). 
These errors occurred when I used the **socketClient.PerpetualFuturesApi.SubscribeToUserDataUpdatesAsync** method with any subscriptions.
![123](https://github.com/JKorf/BingX.Net/assets/40500500/ad39183f-14be-4823-9f7d-8f67d8863539)

**Comment by JKorf** [comment]
Hi, I don't think that exception is related. It's handled internally and caused by the server sending the literal string 'Ping' instead of a json message.

I just tried to place an order and it seems to work for me, can you provide me with the code and parameters you use?

**Comment by Akunin88** [comment]
This started working normally while I'm prepared a test project 🤯
But it didn't work normally a few hours ago. I'll try to reproduce this problem tomorrow.
Here's a test project
[ConsoleTest.zip](https://github.com/user-attachments/files/15859317/ConsoleTest.zip)

**Comment by JKorf** [comment]
That probably means there was indeed an error while parsing the update, but its hard to say what it was when its working now haha. Please let me know if it doesn't work again/you figure out what this issue is

**Comment by Akunin88** [comment]
I couldn't found the reason why this was happening. But sometimes it occurs (about in 2% ccases, more often with market orders).

I found another bug: **clientOrderId will not be returned with updates in the user stream**.
I attach test project
[ConsoleTest2.zip](https://github.com/user-attachments/files/15874869/ConsoleTest2.zip)
![1234](https://github.com/JKorf/BingX.Net/assets/40500500/1e7dfe74-2ded-4583-93aa-5d586539d08f)

**Comment by JKorf** [comment]
I assume you're using the SpotApi then? I checked the docs, but it listed there either, so I guess it's not returned from the server. Even though it is in the futures API.

**Comment by Akunin88** [comment]
I'm using futures api (**RestClient.PerpetualFuturesApi.Trading.PlaceOrderAsync** method)
Seems like server does not return **clientOrderId**.

**Comment by JKorf** [comment]
I had some troubles implementing it initially, but yeah I'll have a look at it again

**Comment by JKorf** [comment]
I've added it in the latest version, seems to work correctly now :)

**Comment by Akunin88** [comment]
I've tested both trade direction, placing limit orders with SL and TP values.
Looks like it works perfectly :)
Thank you!

**Comment by Akunin88** [comment]
I've tested both trade direction, placing limit orders with SL and TP values. Looks like it works perfectly :)
Thank you!
